#week1-3.py
import time

r=1.2
print("퐁", end="")
time.sleep(r/2)
print("당", end=" ")
time.sleep(r/2)
print("퐁", end="")
time.sleep(r/2)
print("당", end=" ")
time.sleep(r/2)
print("돌", end = "")
time.sleep(r/2)
print("을", end=" ")
time.sleep(r/2)
print("던", end="")
time.sleep(r/4)
print("지", end = "")
time.sleep(r/4)
print("자")
time.sleep(r/4)

print("누", end="")
time.sleep(r/2)
print("나", end=" ")
time.sleep(r/2)
print("몰", end="")
time.sleep(r/2)
print("래", end=" ")
time.sleep(r/2)
print("돌", end = "")
time.sleep(r/2)
print("을", end=" ")
time.sleep(r/2)
print("던", end="")
time.sleep(r/4)
print("지", end = "")
time.sleep(r/4)
print("자", end=" ")
time.sleep(r/4)

